language: python

python:
    - 2.7

env:
    DJANGO_VERSION=1.9.2

before_install:
    - "echo '## Installing dependencies'"
    - "sudo apt-get update"
    - "sudo apt-get install -y xorg xfonts-75dpi"
    - "echo '## Downloading wkhtmltopdf'"
    - "wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-wheezy-amd64.deb"
    - "echo '## Installing wkhtmltox'"
    - "sudo dpkg -i wkhtmltox-0.12.2.1_linux-wheezy-amd64.deb"

install:
    - pip install pdfkit==0.5.0 django==$DJANGO_VERSION 

script:
    - python runtests.py
